[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.20"

[[constraint]]
  branch = "master"
  name = "github.com/erikdubbelboer/gspt"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true
